[book]
title = "Proton 0.3.0"
language = "zh"
src = "../content/zh"

[build]
build-dir = "../dist/zh"

[output.html]
theme = "../theme"
site-url = "/proton/zh/"
git-repository-url = "https://github.com/moonbit-community/proton"

[output.html.redirect]
"first-app.html" = "tutorial/first-app.html"
"isomorphic.html" = "tutorial/isomorphic.html"
