#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";

const IDENTIFIER_PATTERN = /^[a-z][a-z0-9_]*$/;

function fail(message) {
  console.error(message);
  process.exit(1);
}

function usage() {
  fail("Usage: node ./scripts/embed_asset.mjs <input> <output> <identifier>");
}

function escapeMoonBitLine(line) {
  return line.replace(/\r/g, "");
}

function main() {
  const [, , inputArg, outputArg, identifier] = process.argv;
  if (!inputArg || !outputArg || !identifier) {
    usage();
  }
  if (!IDENTIFIER_PATTERN.test(identifier)) {
    fail(`Invalid MoonBit identifier: ${identifier}`);
  }

  const inputPath = path.resolve(inputArg);
  const outputPath = path.resolve(outputArg);
  const text = fs.readFileSync(inputPath, "utf8");
  const lines = text.split(/\n/);

  const output = [
    "// Generated by scripts/embed_asset.mjs, do not edit.",
    "",
    "///|",
    `let ${identifier} : String =`,
    ...lines.map((line) => `  #|${escapeMoonBitLine(line)}`),
    "",
  ].join("\n");

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, output);
}

main();
