#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");

const templateRoot = path.join(repoRoot, "cli", "new", "templates", "counter", "files");
const outputPath = process.argv[2]
  ? path.resolve(process.argv[2])
  : path.join(repoRoot, "cli", "new", "templates.generated.mbt");

const preferredOrder = [
  "moon.mod.mtpl",
  "moon.proton.mtpl",
  "app/moon.pkg.mtpl",
  "app/main.mbt.mtpl",
  "app/app.html.mtpl",
  "extensions/counter/moon.pkg.mtpl",
  "extensions/counter/counter.mbt.mtpl",
  "extensions/counter/README.mbt.md.mtpl",
  "AGENTS.md.mtpl",
  "README.mbt.md.mtpl",
  ".gitignore.mtpl",
  "LICENSE.mtpl",
];

function toPosixPath(filePath) {
  return filePath.split(path.sep).join("/");
}

function walk(dir) {
  const files = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const entryPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...walk(entryPath));
    } else if (entry.isFile() && entry.name.endsWith(".mtpl")) {
      files.push(entryPath);
    }
  }
  return files;
}

function moonString(value) {
  return JSON.stringify(value);
}

function moonMultilineString(value) {
  const normalized = value.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  const lines = normalized.endsWith("\n")
    ? normalized.slice(0, -1).split("\n")
    : normalized.split("\n");
  return lines.map((line) => `  #|${line}`).join("\n") + "\n  #|\n";
}

function outputRelativePath(templateRelativePath) {
  return templateRelativePath.slice(0, -".mtpl".length);
}

function sortedTemplates() {
  const discovered = walk(templateRoot).map((file) => {
    const relative = toPosixPath(path.relative(templateRoot, file));
    return { file, relative };
  });
  const byRelative = new Map(discovered.map((item) => [item.relative, item]));
  const ordered = [];
  for (const relative of preferredOrder) {
    const item = byRelative.get(relative);
    if (!item) {
      throw new Error(`Missing template listed in preferred order: ${relative}`);
    }
    ordered.push(item);
    byRelative.delete(relative);
  }
  const extra = [...byRelative.values()].sort((a, b) =>
    a.relative.localeCompare(b.relative),
  );
  return [...ordered, ...extra];
}

const templates = sortedTemplates();
const out = [];
out.push("// Generated by scripts/generate_new_templates.mjs. Do not edit by hand.");
out.push("");
out.push("///|");
out.push("fn generated_template_specs() -> Array[TemplateSpec] {");
out.push("  [");

for (const item of templates) {
  const source = fs.readFileSync(item.file, "utf8");
  out.push("    {");
  out.push(`      output_path: ${moonString(outputRelativePath(item.relative))},`);
  out.push(`      template_name: ${moonString(item.relative)},`);
  out.push("      template_source: (");
  out.push(moonMultilineString(source).replace(/^/gm, "        ").trimEnd());
  out.push("      ),");
  out.push("    },");
}

out.push("  ]");
out.push("}");
out.push("");

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, out.join("\n"), "utf8");
