#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");
const sourcePath = path.join(repoRoot, "cefsetup", "requirements.json");
const source = JSON.parse(fs.readFileSync(sourcePath, "utf8"));
const cefsetupManifest = fs.readFileSync(
  path.join(repoRoot, "cefsetup", "moon.mod"),
  "utf8",
);
const releaseVersion = cefsetupManifest.match(/^version\s*=\s*"([^"]+)"/m)?.[1];
if (!releaseVersion) {
  throw new Error("cefsetup/moon.mod is missing its version");
}

if (source.schema_version !== 1) {
  throw new Error("runtime requirements schema_version must be 1");
}

const platforms = Object.entries(source.platforms);
for (const [id, requirement] of platforms) {
  if (!/^[a-z0-9-]+$/.test(id)) {
    throw new Error(`invalid runtime platform id: ${id}`);
  }
  if (requirement.supported) {
    if (!/^[A-Za-z0-9_.+-]+$/.test(requirement.archive)) {
      throw new Error(`invalid CEF archive name for ${id}`);
    }
    if (!/^[0-9a-f]{64}$/.test(requirement.sha256)) {
      throw new Error(`invalid CEF SHA-256 for ${id}`);
    }
  }
}
const moonString = value => JSON.stringify(value);
const moonBool = value => (value ? "true" : "false");
const functionName = id => `${id.replaceAll("-", "_")}_platform`;

let moon = `// Generated by scripts/generate_runtime_requirements.mjs.\n`;
moon += `// Source: cefsetup/requirements.json.\n\n`;
moon += `///|\npub fn release_version() -> String {\n`;
moon += `  ${moonString(releaseVersion)}\n`;
moon += `}\n\n`;
moon += `///|\nlet default_cef_base_url = ${moonString(source.base_url)}\n\n`;
moon += `///|\nlet runtime_layout_version = ${source.layout_version}\n\n`;
for (const [id, requirement] of platforms) {
  moon += `///|\nfn ${functionName(id)}() -> ProtonPlatform {\n`;
  moon += `  {\n`;
  moon += `    id: ${moonString(id)},\n`;
  moon += `    default_cef_name: ${moonString(requirement.archive)},\n`;
  moon += `    default_cef_sha256: ${moonString(requirement.sha256)},\n`;
  moon += `    supported: ${moonBool(requirement.supported)},\n`;
  moon += `  }\n`;
  moon += `}\n\n`;
}

const moonOutput = process.argv[2] ?? path.join(repoRoot, "cefsetup", "store", "requirements.generated.mbt");
const jsOutput = process.argv[3] ?? path.join(repoRoot, "proton", "cef_requirements.generated.mjs");
fs.writeFileSync(moonOutput, `${moon.trimEnd()}\n`);
fs.writeFileSync(
  jsOutput,
  [
    "// Generated by scripts/generate_runtime_requirements.mjs.",
    "// Source: cefsetup/requirements.json.",
    "",
    `export const cefApiVersion = ${source.cef_api_version};`,
    `export const runtimeLayoutVersion = ${source.layout_version};`,
    `export const runtimeRequirements = Object.freeze(${JSON.stringify(source.platforms, null, 2)});`,
    "",
  ].join("\n"),
);
