#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");
const sourcePath = path.join(
  repoRoot,
  "native/src/engine/cef_common/bridge_bootstrap.js",
);
const outputPath = process.argv[2]
  ? path.resolve(process.argv[2])
  : path.join(
      repoRoot,
      "native/src/engine/cef_common/bridge_bootstrap.generated.h",
    );
const source = fs.readFileSync(sourcePath);
const rows = [];
for (let offset = 0; offset < source.length; offset += 12) {
  rows.push(
    `  ${Array.from(source.subarray(offset, offset + 12), (byte) => `0x${byte.toString(16).padStart(2, "0")}`).join(", ")},`,
  );
}
const output = `// Generated by scripts/generate_bridge_bootstrap.mjs. Do not edit.\n` +
  `#ifndef PROTON_ENGINE_CEF_COMMON_BRIDGE_BOOTSTRAP_GENERATED_H\n` +
  `#define PROTON_ENGINE_CEF_COMMON_BRIDGE_BOOTSTRAP_GENERATED_H\n\n` +
  `static const unsigned char proton_engine_bridge_bootstrap_source[] = {\n` +
  `${rows.join("\n")}\n` +
  `  0x00,\n` +
  `};\n` +
  `static const size_t proton_engine_bridge_bootstrap_source_len = ${source.length};\n\n` +
  `#endif\n`;

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, output);
