[book]
title = "Proton 0.3.0"
language = "en"
src = "content/en"

[build]
build-dir = "dist"

[output.html]
theme = "theme"
site-url = "/proton/"
git-repository-url = "https://github.com/moonbit-community/proton"

[output.html.redirect]
"first-app.html" = "tutorial/first-app.html"
"isomorphic.html" = "tutorial/isomorphic.html"
